//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 2DTrans.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STRING101                   101
#define IDS_RIBBON_PANEL_DIRECTION1     101
#define IDS_RIBBON_DIR_UP               102
#define IDS_RIBBON_DIR_DOWN             103
#define IDS_RIBBON_DIR_LEFT             104
#define IDS_RIBBON_DIR_RIGHT            105
#define IDS_RIBBON_PANEL_DIRECTION2     106
#define IDS_RIBBON_DIR_RDOWN            107
#define IDS_RIBBON_DIR_RUP              108
#define IDS_RIBBON_DIR_LUP              109
#define IDB_WRITESMALL                  110
#define IDS_RIBBON_DIR_LDOWN            110
#define IDB_WRITELARGE                  111
#define ID_DIR_UP                       111
#define IDB_MAIN                        112
#define ID_DIR_DOWN                     112
#define IDB_BUTTONS                     113
#define ID_DIR_LEFT                     113
#define IDB_FILELARGE                   114
#define ID_DIR_RIGHT                    114
#define IDB_FILESMALL                   115
#define ID_DIR_RUP                      115
#define ID_DIR_RDOWN                    116
#define ID_DIR_LUP                      117
#define ID_DIR_LDOWN                    118
#define IDR_POPUP_EDIT                  119
#define IDS_RIBBON_PANEL_DIRECTION3     119
#define ID_STATUSBAR_PANE1              120
#define ID_DIR_SIZE                     120
#define ID_STATUSBAR_PANE2              121
#define IDS_RIBBON_PANEL_ROTATE         121
#define IDS_RIBBON_PANEL_ROTATE1        121
#define IDS_STATUS_PANE1                122
#define IDS_RIBBON_DIR_SIZE             123
#define ID_RIBBON_DIR_SIZE              124
#define ID_ROT_LEFT                     124
#define IDS_RIBBON_ROT_RIGHT            125
#define IDS_RIBBON_ROT_LEFT             126
#define ID_ROT_RIGHT                    127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define ID_ROT_ORIGIN_X                 129
#define IDR_My2DTransTYPE               130
#define ID_ROT_ORIGIN_Y                 130
#define IDS_RIBBON_PANEL_ROTATE2        131
#define ID_ROT_ANGLE                    132
#define IDS_RIBBON_PANEL_ROTATE3        133
#define IDS_RIBBON_MAGNIFY              134
#define IDS_RIBBON_SHRINK               135
#define ID_SCALE_MAGNIFY                136
#define ID_SCALE_SHRINK                 137
#define IDS_RIBBON_PANEL_ROTATE4        138
#define ID_SCALE_RATIO                  139
#define IDS_RIBBON_ORIGINAL             140
#define ID_SCALE_DELTA                  141
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EDIT_MENU                   306
#define IDB_TRANLARGE                   314
#define IDB_ROT_SCALE_LARGE             316
#define ID_STT_TEXT_VER                 1000
#define IDC_NETADDRESS1                 1001
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_SCALE_ORIGINAL               32799
#define IDS_RIBBON_CATEGORY_TRANSLATE   57346
#define IDS_RIBBON_CATEGORY_ROTATE      57347

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
